if(window.opener) {
	let targetUrl = window.opener.location.origin + '/reset';
	fetch(targetUrl, { method: 'POST' }) .then(response => {
    	if(response.ok) {
                window.opener.location.reload();
                window.close();
		}
	});
}