spring:
  application:
    name: "objectmorph-app"
logging:
  level:
    root: INFO
    com:
      github:
        mohamedennahdi: WARN
  file.name: logs/objectmorph-app.log
  pattern:
    console: "[%level] %d{yyyy-MM-dd HH:mm:ss} - %logger{1.} - %msg%n"
    file: "[%level] %d{yyyy-MM-dd HH:mm:ss} - %logger{1.} - %msg%n"