spring:
  application:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
logging:
  level:
    root: INFO
  pattern:
    console: "[%level] %d{yyyy-MM-dd HH:mm:ss} - %logger{1.} - %msg%n"
server:
  max-http-request-header-size: 65000
  servlet:
    session:
      timeout: 600s