# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven to create and publish Docker image

on:
  push:
    tags:
    - '*'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
    - name: settings.xml
      run: cat /home/runner/.m2/settings.xml
    - name: settings.xml
      run: echo 
    - name: Create docker image and push to docker hub (latest version)
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        mvn -B install --file pom.xml
        cd objectmorph-app
        mvn -B spring-boot:build-image --file pom.xml
      env:
        GITHUB_ACTOR: mohamed-ennahdi
        GITHUB_TOKEN: ${{ secrets.ENNAHDI_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Create docker image and push to docker hub (latest version)
      run: |
        REF_NAME=$GITHUB_REF_NAME
        IMAGE_NAME="${REF_NAME//-/-app:}"
        echo $IMAGE_NAME
        docker tag ennahdi/$IMAGE_NAME ennahdi/$IMAGE_NAME
        docker push ennahdi/$IMAGE_NAME
        docker tag ennahdi/$IMAGE_NAME ennahdi/objectmorph-app
        docker push ennahdi/objectmorph-app
